### ISSUE TITLE
On Mobile the autocomplete list is out of viewport

### ISSUE THREAD

**Issue by HRankit** [TunaYagci/vue-mentionable#2]
First of all, great plugin. Was looking for a long time for something like this.

I was trying out the sample code, on mobile devices the list tends to move out of the viewport based on the caret position. Is it possible to keep the list inside the viewport, if so, how?

Also I keep on getting this error,
![Screenshot from 2020-05-08 12-29-31](https://user-images.githubusercontent.com/24871380/81379958-aa970f00-9127-11ea-9314-a3e903f67457.png)

It is something related to size which is my issue. I couldn't find anything in the docs hence, creating the issue.

**Comment by TunaYagci** [comment]
Hey @HRankit thanks for reaching out. I realize it's painful to look at on mobile. It requires some attention. I didn't maintain this project for so much time.  

@Akryum actually did a very good job his project: https://github.com/Akryum/vue-mention 

Why don't you check out that one? I think it works great on mobile as well.

**Comment by HRankit** [comment]
@TunaYagci I acutally did check out @Akryum project. It has some issues too. I first checked out yours. I somehow managed to fix the bug. In some time I'll open a PR. Do take some time out and look into it. This project looks promising. Please don't abandon it.

**Comment by TunaYagci** [comment]
@HRankit well said, thanks! Let me see the if I can get my hands on it this weekend. I'm waiting for that PR.

**Comment by HRankit** [comment]
Issue has been fixed by the recent commit. Closing.
